### ISSUE TITLE
Problems with compiling/running

### ISSUE THREAD

**Issue by DecDuck** [Gaming32/mod-loading-screen#12]
Trying to change the loading screen to something custom, but I can't test the mod. I get this error:
```
 java.lang.RuntimeException: Failed to instantiate language adapter: mod-loading-screen:totallyARealLanguageAdapter
	at net.fabricmc.loader.impl.FabricLoaderImpl.setupLanguageAdapters(FabricLoaderImpl.java:441) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.finishModLoading(FabricLoaderImpl.java:349) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.freeze(FabricLoaderImpl.java:112) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:149) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[?:?]
```

Any ideas?

**Comment by Gaming32** [comment]
Are you running this from an IDE? Are there other mods? Is that the entire error message?

**Comment by DecDuck** [comment]
I'm running from IntelliJ Ultimate, and there's an error about not being able to load the language adaptor. No other mods other than the ones defined in `build.gradle`

**Comment by Gaming32** [comment]
Ah. I've never been able to run Mod Loading Screen from the IDE. I always just build it and run it in a Prism instance.

**Comment by DecDuck** [comment]
Seems to have worked. Any idea why gradle `runClient` doesn't work?

**Comment by Gaming32** [comment]
Loom bug perhaps?

**Comment by BlockySG** [comment]
How is this even compiled in standalone fabric mod form,

Because I can't seem to compile it at all

(IDE) Visual Studio Code

(OS) OpenSUSE Tumbleweed

Java Versions Installed:

8, 17, 21, 25

I want to compile for 1.17.1 (FabricMC)

**Comment by Gaming32** [comment]
What steps are you taking to compile it, and what seems to be the issue? You should be able to just `./gradlew build`, just as with any other Minecraft mod.

**Comment by BlockySG** [comment]
Unfortunately that doesn't seem to be the case with me,

It fails during ./gradlew build

**Comment by BlockySG** [comment]
I can't try again right now as I'm not with my device right now,

I'll probably try again at ~3:30 PM (EST)

**Comment by BlockySG** [comment]
When i do I'll give you the error log

**Comment by BlockySG** [comment]
Yeah I forgot to do it...

I will get around to it eventually

**Comment by BlockySG** [comment]
ok i am doing it now,

i will report back soon

**Comment by BlockySG** [comment]
```
sg5@localhost:~/Documents/GIT/proj1/queinit> java --version
openjdk 17.0.18 2026-01-20
OpenJDK Runtime Environment (build 17.0.18+8-suse-1699-x8664)
OpenJDK 64-Bit Server VM (build 17.0.18+8-suse-1699-x8664, mixed mode, sharing)
sg5@localhost:~/Documents/GIT/proj1/queinit> ./gradlew build
WARNING: A restricted method in java.lang.System has been called
WARNING: java.lang.System::load has been called by net.rubygrapefruit.platform.internal.NativeLibraryLoader in an unnamed module (file:/home/sg5/.gradle/wrapper/dists/gradle-8.13-bin/5xuhj0ry160q40clulazy9h7d/gradle-8.13/lib/native-platform-0.22-milestone-28.jar)
WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled

Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
25.0.2

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 13s
sg5@localhost:~/Documents/GIT/proj1/queinit>
```

**Comment by BlockySG** [comment]
hold on now,
i think this was just me being stupid and not knowing much about java
i think i changed the maven group in my gradle.properties that may be a problem

**Comment by BlockySG** [comment]
Sorry about this...

this may just be my fault as i forked this because i wanted to make some changes to how it looked and perhaps learn some java along the way but i must have messed something up big time

**Comment by BlockySG** [comment]
yep it was my fault

**Comment by BlockySG** [comment]
ok this time i got a different error after starting again with a fresh copy

it seems to happen upon me trying to build for 1.21.8 with fabric 0.18.4

```

sg5@localhost:~/Documents/GIT/proj1/queinit> ./gradlew build

> Configure project :
Fabric Loom: 1.10.5

> Task :compileApiJava
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
/home/sg5/Documents/GIT/proj1/queinit/src/api/java/io/github/gaming32/modloadingscreen/api/LoadingScreenApi.java:8: error: cannot find symbol
import net.fabricmc.loader.impl.entrypoint.EntrypointUtils;
                                          ^
  symbol:   class EntrypointUtils
  location: package net.fabricmc.loader.impl.entrypoint
1 error
3 warnings

> Task :compileApiJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileApiJava'.
> Compilation failed; see the compiler output below.
  warning: [options] source value 8 is obsolete and will be removed in a future release
  warning: [options] target value 8 is obsolete and will be removed in a future release
  warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
  /home/sg5/Documents/GIT/proj1/queinit/src/api/java/io/github/gaming32/modloadingscreen/api/LoadingScreenApi.java:8: error: cannot find symbol
  import net.fabricmc.loader.impl.entrypoint.EntrypointUtils;
                                            ^
    symbol:   class EntrypointUtils
    location: package net.fabricmc.loader.impl.entrypoint
  1 error
  3 warnings

* Try:
> Check your code and dependencies to fix the compilation error(s)
> Run with --scan to get full insights.

BUILD FAILED in 5s
1 actionable task: 1 executed

```

also i did use update-alternatives to change to JDK 21

```

sg5@localhost:~/Documents/GIT/proj1/queinit> java --version
openjdk 21.0.10 2026-01-20
OpenJDK Runtime Environment (build 21.0.10+7-suse-1699-x8664)
OpenJDK 64-Bit Server VM (build 21.0.10+7-suse-1699-x8664, mixed mode, sharing)

```

**Comment by Gaming32** [comment]
The error shows you're using Java 25 with Gradle. Please set your `JAVA_HOME` to a version compatible with this old version of Gradle.

**Comment by BlockySG** [comment]
For me to do that I must run

```
sudo update-alternatives --config java
```

And

```
sudo update-alternatives --config javac
```

And then I must log out and log back in again

I already did this to change to Java 21 before my most recent posted error log.

this time it's something else as after I posted that first error log I figured out the wrong Java version was still being used after I already ran update-alternatives 

I also ran a test compile without changing the Minecraft and fabric versions in order to see if there was any other issues and it built without problems

I'm now trying to build for Minecraft 1.21.8 and the latest Fabric and Fabric API version for this Minecraft version

**Comment by BlockySG** [comment]
The thing I'm probably going to try next is updating loom

**Comment by BlockySG** [comment]
But it's spificly failing at Gradle/fabric-loom task:

:compileApiJava

**Comment by BlockySG** [comment]
I can somewhat understand what it's telling me so I'll just give you the error itself here without the extra spam (sorry about that by the way)

```

/home/sg5/Documents/GIT/proj1/queinit/src/api/java/io/github/gaming32/modloadingscreen/api/LoadingScreenApi.java:8: error: cannot find symbol
  import net.fabricmc.loader.impl.entrypoint.EntrypointUtils;
                                            ^
    symbol:   class EntrypointUtils
    location: package net.fabricmc.loader.impl.entrypoint

```

From what I understand it's saying that it can't find 

net.fabricmc.loader.impl.entrypoint.EntrypointUtils 

Or can't find EntrypointUtils inside of net.fabricmc.loader.impl.entrypoint

**Comment by Gaming32** [comment]
This issue is not the place to get help with the basics of compiling Gradle programs, the basics of using a Linux terminal, or the basics of FabricMC. If you wish to use the mod with Minecraft, please download it from Modrinth, as the same build works for all versions of the game. If you wish to continue trying to compile it yourself, please seek out help other places than this issue tracker.

@DecDuck I believe the original issue has actually been fixed with the introduction of the new `prodClient` task. If it is not fixed, please make a new issue.
