### ISSUE TITLE
Compiled for Java 8 but crashing on it

### ISSUE THREAD

**Issue by thecatcore** [Gaming32/mod-loading-screen#16]
Since 1.0.2, the mod is targeting Java 8, it runs well on Java 17, but crash on Java 8.
In my case, I'm using Fabric Loader 0.14.21.

```
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider jdk.nashorn.api.scripting.NashornScriptEngineFactory not found
[22:19:14] [main/INFO]: Loading Minecraft 1.13.2 with Fabric Loader 0.14.21
[22:19:14] [main/INFO]: Loading 6 mods:
	- fabricloader 0.14.21
	- java 8
	- minecraft 1.13.2
	- mod-loading-screen 1.0.2
	   |-- com_formdev_flatlaf 3.0
	   \-- net_lenni0451_reflect 1.0.2
[ModLoadingScreen] I just want to say... I'm loading *really* early.
[ModLoadingScreen] Opening loading screen
Exception caught from launcher
java.lang.Error: java.lang.RuntimeException: Unable to invoke method startLoadingScreen
	at io.github.gaming32.modloadingscreen.ModLoadingScreen.<clinit>(ModLoadingScreen.java:200)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setupLanguageAdapters(FabricLoaderImpl.java:439)
	at net.fabricmc.loader.impl.FabricLoaderImpl.finishModLoading(FabricLoaderImpl.java:349)
	at net.fabricmc.loader.impl.FabricLoaderImpl.freeze(FabricLoaderImpl.java:112)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:149)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.RuntimeException: Unable to invoke method startLoadingScreen
	at net.lenni0451.reflect.Methods.invoke(Methods.java:53)
	at io.github.gaming32.modloadingscreen.ModLoadingScreen.init(ModLoadingScreen.java:65)
	at io.github.gaming32.modloadingscreen.ModLoadingScreen.<clinit>(ModLoadingScreen.java:198)
	... 11 more
Caused by: java.lang.NoClassDefFoundError: com/formdev/flatlaf/FlatDarkLaf
	at io.github.gaming32.modloadingscreen.ActualLoadingScreen.startLoadingScreen(ActualLoadingScreen.java:129)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at net.lenni0451.reflect.Methods.invoke(Methods.java:50)
	... 13 more
Caused by: java.lang.ClassNotFoundException: com.formdev.flatlaf.FlatDarkLaf
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 16 more
Exiting with ERROR
Process exited with code 2.
```

**Comment by blryface** [comment]
It actually needs java 11
