### ISSUE TITLE
i dont even know (sodium)

### ISSUE THREAD

**Issue by some-du6e** [Gaming32/mod-loading-screen#19]
Uncaught exception in thread "main"
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setupLanguageAdapters(FabricLoaderImpl.java:431)
	at net.fabricmc.loader.impl.FabricLoaderImpl.finishModLoading(FabricLoaderImpl.java:349)
	at net.fabricmc.loader.impl.FabricLoaderImpl.freeze(FabricLoaderImpl.java:112)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:149)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

pretty sure its the latest sodium (this also happened with early loading screen)

**Comment by Gaming32** [comment]
I doubt it's Sodium. Sodium has no control over this kind of thing. Besides, I use latest Sodium with this without issue

**Comment by Gaming32** [comment]
It looks like you have some mod that's injecting other mods. Please send a full log.

**Comment by blryface** [comment]
I think this issue should be closed?

**Comment by Gaming32** [comment]
Yes. Closing due to no response.
